networks:

  # network nat
  - name: kfknat
    forward:
      mode: nat
      port:
        start: 1025
        end: 65535
    bridge:
      name: brkfknat
      stp: on
      delay: 0
    hwaddr: 52:54:00:f7:34:54
    domainname: internal
    ipaddr: 192.168.100.1
    netmask: 255.255.255.0
    dhcp_range:
      start: 192.168.100.2
      end: 192.168.100.253

  # private net
  - name: kfkint
    bridge:
      name: brkfkint
      stp: on
      delay: 0
    hwaddr: 52:54:00:f7:34:57
    domainname: internal
    ipaddr: 192.168.101.1
    netmask: 255.255.255.0
    dhcp_range:
      start: 192.168.101.2
      end: 192.168.101.254