vms:
- name : kfk-dns
  timezone: America/Sao_Paulo
  hostname: 'kfk-dns'
  vcpu: 1
  memory_kib: '1048576' #1gb
  qcow_template_disk_file: '/home/csantana/VirtualMachines/rhel-server-7.8-x86_64-kvm.qcow2'
  qcow_disk_file: '/home/csantana/VirtualMachines/kfk-dns.qcow2'
  root_password: kafka
  networks:
    - name: kfknat
      ip: 192.168.100.2
      dns: 
        - 192.168.100.2
    - name: kfkint
      ip: 192.168.101.2
      dns: 
        - 192.168.101.2

- name : kfk-zoo-01
  timezone: America/Sao_Paulo
  hostname: 'kfk-zoo-01'
  vcpu: 1
  memory_kib: '3145728' #3gb
  qcow_template_disk_file: '/home/csantana/VirtualMachines/rhel-server-7.8-x86_64-kvm.qcow2'
  qcow_disk_file: '/home/csantana/VirtualMachines/kfk-zoo-01.qcow2'
  root_password: kafka
  networks:
    - name: kfknat
      ip: 192.168.100.11
      dns: 
        - 192.168.100.2
    - name: kfkint
      ip: 192.168.101.11
      dns: 
        - 192.168.101.2


- name : kfk-zoo-02
  timezone: America/Sao_Paulo
  hostname: 'kfk-zoo-02'
  vcpu: 1
  memory_kib: '3145728' #3gb
  qcow_template_disk_file: '/home/csantana/VirtualMachines/rhel-server-7.8-x86_64-kvm.qcow2'
  qcow_disk_file: '/home/csantana/VirtualMachines/kfk-zoo-02.qcow2'
  root_password: kafka
  networks:
    - name: kfknat
      ip: 192.168.100.12
      dns: 
        - 192.168.100.2
    - name: kfkint
      ip: 192.168.101.12
      dns: 
        - 192.168.101.2

- name : kfk-zoo-03
  timezone: America/Sao_Paulo
  hostname: 'kfk-zoo-03'
  vcpu: 1
  memory_kib: '3145728' #3gb
  qcow_template_disk_file: '/home/csantana/VirtualMachines/rhel-server-7.8-x86_64-kvm.qcow2'
  qcow_disk_file: '/home/csantana/VirtualMachines/kfk-zoo-03.qcow2'
  root_password: kafka
  networks:
    - name: kfknat
      ip: 192.168.100.13
      dns: 
        - 192.168.100.2
    - name: kfkint
      ip: 192.168.101.13
      dns: 
        - 192.168.101.2


- name : kfk-kafka-01
  timezone: America/Sao_Paulo
  hostname: 'kfk-kafka-01'
  vcpu: 1
  memory_kib: '3145728' #3gb
  qcow_template_disk_file: '/home/csantana/VirtualMachines/rhel-server-7.8-x86_64-kvm.qcow2'
  qcow_disk_file: '/home/csantana/VirtualMachines/kfk-kafka-01.qcow2'
  root_password: kafka
  networks:
    - name: kfknat
      ip: 192.168.100.21
      dns: 
        - 192.168.100.2
    - name: kfkint
      ip: 192.168.101.21
      dns: 
        - 192.168.101.2


- name : kfk-kafka-02
  timezone: America/Sao_Paulo
  hostname: 'kfk-kafka-02'
  vcpu: 1
  memory_kib: '3145728' #3gb
  qcow_template_disk_file: '/home/csantana/VirtualMachines/rhel-server-7.8-x86_64-kvm.qcow2'
  qcow_disk_file: '/home/csantana/VirtualMachines/kfk-kafka-02.qcow2'
  root_password: kafka
  networks:
    - name: kfknat
      ip: 192.168.100.22
      dns: 
        - 192.168.100.2
    - name: kfkint
      ip: 192.168.101.22
      dns: 
        - 192.168.101.2


- name : kfk-kafka-03
  timezone: America/Sao_Paulo
  hostname: 'kfk-kafka-03'
  vcpu: 1
  memory_kib: '3145728' #3gb
  qcow_template_disk_file: '/home/csantana/VirtualMachines/rhel-server-7.8-x86_64-kvm.qcow2'
  qcow_disk_file: '/home/csantana/VirtualMachines/kfk-kafka-03.qcow2'
  root_password: kafka
  networks:
    - name: kfknat
      ip: 192.168.100.23
      dns: 
        - 192.168.100.2
    - name: kfkint
      ip: 192.168.101.23
      dns: 
        - 192.168.101.2

- name : kfk-kafka-04
  timezone: America/Sao_Paulo
  hostname: 'kfk-kafka-04'
  vcpu: 1
  memory_kib: '3145728' #3gb
  qcow_template_disk_file: '/home/csantana/VirtualMachines/rhel-server-7.8-x86_64-kvm.qcow2'
  qcow_disk_file: '/home/csantana/VirtualMachines/kfk-kafka-04.qcow2'
  root_password: kafka
  networks:
    - name: kfknat
      ip: 192.168.100.24
      dns: 
        - 192.168.100.2
    - name: kfkint
      ip: 192.168.101.24
      dns: 
        - 192.168.101.2


- name : kfk-influxdb
  timezone: America/Sao_Paulo
  hostname: 'kfk-influxdb'
  vcpu: 1
  memory_kib: '3145728' #3gb
  qcow_template_disk_file: '/home/csantana/VirtualMachines/rhel-server-7.8-x86_64-kvm.qcow2'
  qcow_disk_file: '/home/csantana/VirtualMachines/kfk-influxdb.qcow2'
  root_password: kafka
  networks:
    - name: kfknat
      ip: 192.168.100.31
      dns: 
        - 192.168.100.2
    - name: kfkint
      ip: 192.168.101.31
      dns: 
        - 192.168.101.2

- name : kfk-grafana
  timezone: America/Sao_Paulo
  hostname: 'kfk-grafana'
  vcpu: 1
  memory_kib: '3145728' #3gb
  qcow_template_disk_file: '/home/csantana/VirtualMachines/rhel-server-7.8-x86_64-kvm.qcow2'
  qcow_disk_file: '/home/csantana/VirtualMachines/kfk-grafana.qcow2'
  root_password: kafka
  networks:
    - name: kfknat
      ip: 192.168.100.32
      dns: 
        - 192.168.100.2
    - name: kfkint
      ip: 192.168.101.32
      dns: 
        - 192.168.101.2

