---
#- name: cria as máquinas virtuais
#  hosts: 
#    - localhost
#  vars_files:
#    - vars/networks.yaml
#    - vars/vms.yaml
#  roles:
#    - network-create
#    - vms-create
#    - vms-start
#    - copy-ssh-keys
#
#- name: configura todas as maquinas com config default
#  hosts: 
#    - all
#  vars_files:
#    - ../../vars/hrel_subscription.yaml
#    - vars/networks.yaml
#    - vars/vms.yaml
#    - vars/ntp-client.yaml
#  roles:
#    - config-fast-ssh
#    - subscription-manager-register
#    - vms-common-config
#    - ntp-client    
#    - config-high-performance
##    - disable-transparent-huge-pages
#    - config-jumbo-frames
#    - config-ring-buffer
#
#- name: instala servidor dns
#  hosts: 
#    - dns
#  vars_files:
#    - vars/dns.yaml
#  roles:
#    - bind
#
#- name: configura dns
#  hosts: 
#    - all
#  vars_files:
#    - vars/vms.yaml
#  roles:
#    - configure-dns

- name: instala amq-streams
  hosts:
    - zookeeper
    - kafka
  roles:
    #- vms-common-config
    - install-jdk-11
    - install-amq-streams

- name: configura amq-streams zookeeper hosts
  hosts:
    - zookeeper
  roles:
    - configure-amq-streams-zookeeper
  
- name: configura amq-streams kafka hosts
  hosts:
    - kafka
  roles:
    - configure-amq-streams-kafka
  